on:
  push:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: "Login to Docker hub"
        run: docker login --username ${{ secrets.USERNAME_DOCKER }} --password ${{ secrets.TOKEN_DOCKER }}

      - name: "Building docker image"
        run: docker build -t ${{ secrets.USERNAME_DOCKER }}/projectos .  

      - name: "Pushing to Docker hub"
        run: docker push ${{ secrets.USERNAME_DOCKER }}/projectos
